//Leer
###
GET https://my-api-rest.fly.dev/api HTTP/1.1

//Buscar
###
GET https://my-api-rest.fly.dev/api/ver/1 HTTP/1.1

//Insertar
###
POST https://my-api-rest.fly.dev/api/nuevo HTTP/1.1
Content-Type: application/json

{
"id":1,
"nombre":"Hola",
"img":"url image",
"precio":9082,
"fechaCracion":"19-02-2023"

}

//Actualizar
###
PUT https://my-api-rest.fly.dev/api/actualizar/1 HTTP/1.1
Content-Type: application/json

{

"nombre":"Estadisticas",
"img":"url image",
"precio":990,
"fechaCracion":"19-02-2023"

}

//Eliminar
### 
DELETE https://my-api-rest.fly.dev/api/eliminar/2 HTTP/1.1

